/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto.continuada01.dados;

import java.util.Random;

/**
 *
 * @author Mateus
 */
public class Dados extends javax.swing.JFrame {

    Double clock = 0.00;
    Double memory = 0.00;
    Integer percent1 = 0;
    Integer percent2 = 0;
    Integer percent3 = 0;
    Integer minCpu = 0;
    Integer maxCpu = 0;
    Integer totalCpu = 0;
    Integer totalDisc = 0;
    Integer totalMem = 0;
    Integer minDisc = 0;
    Integer maxDisc = 0;
    Integer avgDisc = 0;
    Integer minMem = 0;
    Integer maxMem = 0;
    Integer avgMem = 0;
    Integer cont = 1;
    Random random = new Random();
        
    public Dados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRead = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblMinCpu = new javax.swing.JLabel();
        lblMaxCpu = new javax.swing.JLabel();
        lblAvgCpu = new javax.swing.JLabel();
        progressCpu = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lblPercent1 = new javax.swing.JLabel();
        txtValClock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        progressDisc = new javax.swing.JProgressBar();
        lblAvgDisc = new javax.swing.JLabel();
        lblMaxDisc = new javax.swing.JLabel();
        lblMinDisc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPercent2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        progressMem = new javax.swing.JProgressBar();
        lblMaxMem = new javax.swing.JLabel();
        lblAvgMem = new javax.swing.JLabel();
        lblPercent3 = new javax.swing.JLabel();
        lblMinMem = new javax.swing.JLabel();
        txtMemory = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(220, 220, 220));

        btnRead.setBackground(new java.awt.Color(40, 44, 46));
        btnRead.setForeground(new java.awt.Color(255, 255, 255));
        btnRead.setText("Fazer leitura dos dados");
        btnRead.setBorder(null);
        btnRead.setBorderPainted(false);
        btnRead.setMargin(new java.awt.Insets(8, 14, 8, 14));
        btnRead.setPreferredSize(new java.awt.Dimension(150, 30));
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 139, 231), 2, true));
        jPanel1.setForeground(new java.awt.Color(39, 139, 231));

        lblMinCpu.setText("Mínimo: 0");

        lblMaxCpu.setText("Máximo: 0");

        lblAvgCpu.setText("Média: 0");

        progressCpu.setForeground(new java.awt.Color(30, 106, 230));

        jLabel1.setBackground(new java.awt.Color(14, 15, 16));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CPU");

        lblPercent1.setText("0%");

        txtValClock.setText("2,9GHz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPercent1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValClock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progressCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinCpu)
                    .addComponent(lblMaxCpu)
                    .addComponent(lblAvgCpu))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPercent1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValClock)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMinCpu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaxCpu)
                            .addComponent(progressCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvgCpu)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 150, 8), 2, true));

        progressDisc.setForeground(new java.awt.Color(11, 192, 38));

        lblAvgDisc.setText("Média: 0");

        lblMaxDisc.setText("Máximo: 0");

        lblMinDisc.setText("Mínimo: 0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Disco (C:)");

        lblPercent2.setText("0%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblPercent2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvgDisc)
                    .addComponent(lblMinDisc)
                    .addComponent(lblMaxDisc))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(lblPercent2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMinDisc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaxDisc)
                            .addComponent(progressDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvgDisc)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(86, 48, 141), 2, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Memória");

        progressMem.setForeground(new java.awt.Color(98, 34, 115));

        lblMaxMem.setText("Máximo: 0");

        lblAvgMem.setText("Média: 0");

        lblPercent3.setText("0%");

        lblMinMem.setText("Mínimo: 0");

        txtMemory.setText("0,0/15,9GB");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(progressMem, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblPercent3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMemory)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvgMem)
                    .addComponent(lblMaxMem)
                    .addComponent(lblMinMem))
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMinMem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMaxMem)
                            .addComponent(progressMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvgMem))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPercent3)
                            .addComponent(txtMemory))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setText("Desempenho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel4)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        percent1 = random.nextInt(101);
        percent2 = random.nextInt(101);
        percent3 = random.nextInt(101);
        memory =  (15.9*percent3)/100;
        memory = Math.round(memory*100.0)/100.0;
        
        lblPercent1.setText(percent1 + "%");
        lblPercent2.setText(percent2 + "%");
        lblPercent3.setText(percent3 + "%");
        txtMemory.setText(memory + "/15.9GB");
        
        if(cont == 1){
            minCpu = percent1;
        }else if(percent1 < minCpu){
            minCpu = percent1;
        }
        
        if(cont == 1){
            maxCpu = percent1;
        }else if(percent1 > maxCpu){
            maxCpu = percent1;
        }
        
        if(cont == 1){
            minDisc = percent2;
        }else if(percent2 < minDisc){
            minDisc = percent2;
        }
        
        if(cont == 1){
            maxDisc = percent2;
        }else if(percent2 > maxDisc){
            maxDisc = percent2;
        }
        
        if(cont == 1){
            minMem = percent3;
        }else if(percent3 < minMem){
            minMem = percent3;
        }
        
        if(cont == 1){
            maxMem = percent3;
        }else if(percent3 > maxMem){
            maxMem = percent3;
        }
        
        progressCpu.setValue(percent1);
        progressDisc.setValue(percent2);
        progressMem.setValue(percent3);
        totalCpu += percent1;
        totalDisc += percent2;
        totalMem += percent3;
        Integer avgCpu = totalCpu/cont;
        Integer avgDisc = totalDisc/cont;
        Integer avgMem = totalMem/cont;
        lblMinCpu.setText("Mínimo: " + minCpu + "%");
        lblMaxCpu.setText("Máximo: " + maxCpu + "%");
        lblAvgCpu.setText("Média: " + avgCpu + "%");
        lblMinDisc.setText("Mínimo: " + minDisc + "%");
        lblMaxDisc.setText("Máximo: " + maxDisc + "%");
        lblAvgDisc.setText("Média: " + avgDisc + "%");
        lblMinMem.setText("Mínimo: " + minMem + "%");
        lblMaxMem.setText("Máximo: " + maxMem + "%");
        lblAvgMem.setText("Média: " + avgMem + "%");
        cont++;
    }//GEN-LAST:event_btnReadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRead;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAvgCpu;
    private javax.swing.JLabel lblAvgDisc;
    private javax.swing.JLabel lblAvgMem;
    private javax.swing.JLabel lblMaxCpu;
    private javax.swing.JLabel lblMaxDisc;
    private javax.swing.JLabel lblMaxMem;
    private javax.swing.JLabel lblMinCpu;
    private javax.swing.JLabel lblMinDisc;
    private javax.swing.JLabel lblMinMem;
    private javax.swing.JLabel lblPercent1;
    private javax.swing.JLabel lblPercent2;
    private javax.swing.JLabel lblPercent3;
    private javax.swing.JProgressBar progressCpu;
    private javax.swing.JProgressBar progressDisc;
    private javax.swing.JProgressBar progressMem;
    private javax.swing.JLabel txtMemory;
    private javax.swing.JLabel txtValClock;
    // End of variables declaration//GEN-END:variables
}
